title: Freeloop's Blog
description: 技术博客，分享编程与思考
url: "https://freeloop001.github.io"
baseurl: "/blog"
future: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    rouge:
      theme: github
  auto_ids: true
  auto_id_prefix: ""
